TEST_VALUE:
  name: cookie

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a258e6c3aa38d00d
  FEISHU_APP_SECRET: MTdkmH1yOJJRhIwvO1Oo1epupROtGOIv

APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY

MONGODB_CONFIG:
  # name: "fast_gateway"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://superice:superice123@47.111.240.180:12001/gateway?authSource=gateway"   # 数据库链接地址
  # username: "superice"                   # 数据库链接用户名
  # password: "superice123"                 # 数据库链接密码
  database: "gateway"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: true                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能

MYSQL_CONFIG:
  name: "iceage-mysql"
  type: "mysql"
  host: "47.111.240.180"
  port: 12000
  username: "root"
  password: "8jdgi5anfkr2gm00rza1wvhjm2i9o4fl"
  database: "nestjs-backend"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true